<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\fluxel\fluxel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="flustix.Midori.Database.MongoDB" Version="2026.505.0" />
    </ItemGroup>

</Project>
